import 'package:flutter/material.dart';

class SowarPage extends StatefulWidget {
  const SowarPage({super.key});

  @override
  State<SowarPage> createState() => _SowarPageState();
}

class _SowarPageState extends State<SowarPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        toolbarHeight: 55,
        centerTitle: true,
        elevation: 0,
        backgroundColor: Colors.grey.shade300,
        title: const Padding(
          padding: EdgeInsets.symmetric(vertical: 6),
          child: Text(
            "السور",
            style: TextStyle(
                fontSize: 25, fontWeight: FontWeight.bold, color: Colors.black),
          ),
        ),
      ),
      body:SingleChildScrollView( 
        child: Center(
        child: ListView(
          padding: EdgeInsets.zero,
          children: [
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الفاتحة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('البقرة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text("ال عمران",
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text(' النساء',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الماءدة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text("الانعام",
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الاعراف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الانفال',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التوبة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('يونس',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('هود',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('يوسف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الرعد',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('ابراهيم ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الحجر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النحل',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الاسراء',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الكهف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('مريم',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('طه',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الانبياء ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الحج ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المومنون ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النور ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الفرقان ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الشعراء',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النمل ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('القصص',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('العنكبوت ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الروم',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('لقمان',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('السجدة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text("الاحزاب",
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text(' سبأ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('فاطر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text("يس",
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الصافات',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('ص',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الزمر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('غافر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('فصلت',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الشوري',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الزخرف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الدخان',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الجاثية',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الاحقاف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('محمد',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الاحقاف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الفتح',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الحجرات',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('ق',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الذاريات',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الطور',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النجم',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('القمر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الرحمن',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الواقعة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الحديد',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المجادلة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الحشر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الممتحنه',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الصف',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الجمعة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المنافقون',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التغابن',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الطلاق',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التحريم',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الملك',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('القلم',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الحاقة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المعارج',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('نوح',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الجن',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المزمل',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المدثر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('القيامة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التغابن',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الانسان',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المرسلات',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النبأ',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النازعات',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('عبس',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التكوير',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الانفطار',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المطففين',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الانشقاق',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('البروج',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الطارق',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الاعلي',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الغاشية',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الفجر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('البلد',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الشمس',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الليل',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الضحي',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الشرح',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التين',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('العلق',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('القدر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('البينة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الزلزلة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('العاديات',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('القارعة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('التكاثر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('العصر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الهمزة',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الفيل',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('قريش',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الماعون',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الكوثر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الكافرون',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('النصر',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('المسد',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الاخلاص',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الفلق',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
            ListTile(
              leading: Icon(Icons.list_alt, color: Colors.grey),
              title: Text('الناس',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              onTap: () => {},
            ),
          ],
          ),
        ),
      ),
    );
  }
}
